name: Java17v3

on:
  push:
    paths:
      - '*/*/java17v3.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        update: [17, 17.0.3, 17.0.2, 17.0.1, 17.0.0, 17.0.0-ea.2, 17-ea]
        package: [jdk, jre]
        exclude:
          - {update: 17.0.0-ea.2, package: jre}
          - {update: 17-ea, package: jre}
      fail-fast: false
      max-parallel: 6
    name: ${{ matrix.package }} ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-package: ${{ matrix.package }}
        java-version: ${{ matrix.update }}
    - name: java -version
      run: java -version
