name: Java16

on:
  push:
    paths:
      - '*/*/java16.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */8 * * *'
      
jobs:
  java16:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [16, 16.0.0, 16.0.0-ea, 16.0.0-ea.5, 16-ea]
        package: [jdk, jre]
        exclude:
          - {update: 16.0.0-ea, package: jre}
          - {update: 16.0.0-ea.5, package: jre}
          - {update: 16-ea, package: jre}
      fail-fast: false
      max-parallel: 6
    name: JDK ${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.update }}
    - name: java -version
      run: java -version
